name: ZCLI Pipeline

on: 
  #Triggers the workflow
  push: 
      branches:
        [ main ]
  workflow_dispatch:

jobs:

  build: 

    runs-on: ubuntu-latest

    env: 
      ZENDESK_SUBDOMAIN: ${{  secrets.SUBDOMAIN  }}
      ZENDESK_EMAIL:  ${{  secrets.EMAIL  }}
      ZENDESK_PASSWORD: ${{  secrets.PASSWORD  }}
    
    strategy:
      matrix:
        node-version: [16.x]

    steps: 
      - name: Get Repo
        uses: actions/checkout@v2
      - name: Use Node.js ${{  matrix.node-version  }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{  matrix.node-version  }}
      - name: Install Dependencies
        run: sudo apt-get install libsecret-1-dev
      - name: Install ZCLI
        run: npm i @zendesk/zcli -g 
      - name: Derploy the app? 
        run: zcli apps:update
